Refactoring to prepare for new distribution function approach
ergodicio/tsadar pull request #76
Opened 2024-12-02 15:33 UTC by joglekara

2024-12-02 18:06 UTC, almilder commented on tsadar/model/TSFitter.py
fe normalization in weights to params needs to be fixed

2024-12-02 19:13 UTC, joglekara commented on tsadar/model/TSFitter.py
what do you mean by fixed? Is something already broken? I don't think any of that logic is altered here, just the variable names

2024-12-17 16:20 UTC, almilder commented on configs/1d-new/defaults.yaml
I think having a set of 1d input deck and a set of 1d-new is a recipe for confusion

2024-12-17 16:25 UTC, joglekara commented on configs/1d-new/defaults.yaml
good catch, needs removal

2024-12-17 16:25 UTC, almilder commented on requirements.txt
if pyhdf is removed what are we using for loading data?

2024-12-17 16:28 UTC, almilder commented on tests/configs/time_test_defaults.yaml
spectype: d?

2024-12-17 16:29 UTC, joglekara commented on requirements.txt
I think I just removed it from requirements because its not pip installable and requires a conda install

2024-12-17 16:29 UTC, joglekara commented on tests/configs/time_test_defaults.yaml
should say 1d

2024-12-17 16:36 UTC, almilder commented on tests/test_forward/test_1d.py
Why does this use the 1d-new inputs instead of the test_angular_1d?

2024-12-17 16:41 UTC, almilder commented on tests/test_forward/test_1d.py
What aspect of 1D is this testing?

2024-12-17 16:43 UTC, almilder commented on tests/test_forward/test_angular_1d.py
Thomson diagnostic doesnt do lines 43-59?

2024-12-17 16:44 UTC, almilder commented on tests/test_forward/test_angular_2d.py
Thomson diagnostic doesnt do lines 43-59?

2024-12-17 16:46 UTC, almilder commented on tests/test_inverse/test_1d_random.py
again i wouldnt use the 1d-new input decks, use dedicated ones from the tests

2024-12-17 16:51 UTC, almilder commented on tests/test_inverse/test_arts1d_random.py
same points as the 1d random

2024-12-17 17:08 UTC, almilder commented on tsadar/core/physics/form_factor.py
lams may be a recreation of lamAxis, we should check and remove lams if that is the case

2024-12-17 17:13 UTC, almilder commented on tsadar/core/physics/form_factor.py
We need to investigate the result returned by rotate, last time i looked it had bad numerical artifacts

2024-12-17 17:20 UTC, almilder commented on tsadar/core/physics/form_factor.py
it was in the returned 1d edfs so it may bave been a different function

2024-12-17 17:39 UTC, almilder commented on tsadar/core/physics/irf.py
Looks fine but i want to check the behavior of the amplitude normalization especially for ARTS. Want to make sure we preserve the amplitude dependence on angle

2024-12-17 17:44 UTC, almilder commented on tsadar/data_handleing/calibrations/sa_table.py
Did this get moved? cause it is still needed

2024-12-17 17:46 UTC, almilder commented on tsadar/distribution_functions/gen_num_dist_func.py
isn't this supplanted by modules?

2024-12-17 17:48 UTC, almilder commented on tsadar/forward/calc_series.py
just breaking this out of fitter?

2024-12-17 17:49 UTC, almilder commented on tsadar/inverse/fitter.py
got rid of the checks in 84-107?

2024-12-17 17:54 UTC, almilder commented on tsadar/inverse/fitter.py
lets replace the 1d_adam with the behavior from angular optax (select-able minimizer and exit conditions), this might allow them to be merged, not sure

2024-12-17 17:57 UTC, almilder commented on tsadar/inverse/fitter.py
lines 396-410 are needed to prevent repeating actions in multiplexed ARTS data which causes error, is this handled elsewhere now?

2024-12-17 17:58 UTC, almilder commented on tsadar/inverse/fitter.py
Nevermind this is a new function at the bottom

2024-12-17 17:58 UTC, almilder commented on tsadar/inverse/fitter.py
then lets remove scipy

2024-12-17 18:00 UTC, almilder commented on tsadar/utils/data_handling/calibration.py
looks like this is where the probe beam selection went

2024-12-17 18:01 UTC, almilder commented on tsadar/utils/data_handling/load_ts_data.py
still depends on pyhdf which was removed?

2024-12-17 18:03 UTC, almilder commented on tsadar/utils/plotting/lineout_plot.py
why are we getting rid of the ylimit?

2024-12-17 18:03 UTC, almilder commented on tsadar/utils/plotting/ele_fit_and_data (1).nc
this should probably be removed

2024-12-17 18:05 UTC, almilder commented on tsadar/utils/plotting/plotters.py
ln 33-36 will prevent logging of the distribution function

2024-12-17 18:08 UTC, almilder commented on tsadar/utils/plotting/plotters.py
an additional contour plot of fe was added for 2dfe?

2024-12-17 18:10 UTC, almilder commented on tsadar/utils/plotting/plotters.py
vmin and vmax were removed from 2d fit_data plots? and hardcoded for angular?

2024-12-17 18:13 UTC, almilder commented on tsadar/utils/process/postprocess.py
looks like there were some changes here, lets go over it since there is no diff

2024-12-17 18:17 UTC, almilder commented on tsadar/inverse/loss_function.py
lets think about whether this is still the best structure

2024-12-17 18:18 UTC, almilder requested changes
Lots for us to discuss

2024-12-17 21:03 UTC, joglekara commented on tsadar/forward/calc_series.py
yup

2024-12-17 21:03 UTC, joglekara commented on tsadar/distribution_functions/gen_num_dist_func.py
yup, needs to be removed

2024-12-17 21:03 UTC, joglekara commented on tsadar/distribution_functions/dist_functional_forms.py
yup, needs to be removed

2024-12-17 21:04 UTC, joglekara commented on tsadar/utils/data_handling/calibration.py
yup

2024-12-18 19:04 UTC, joglekara commented on tests/test_forward/test_1d.py
that the forward pass recovers some (this) version from the past

2024-12-18 19:05 UTC, joglekara commented on tests/test_forward/test_angular_1d.py
I think I grabbed this directly from `calc_series()` so I don't think it did. But as we discussed, we should probably have `ThomsonDiagnostic` handle it.

2024-12-18 19:06 UTC, joglekara commented on tests/test_forward/test_angular_2d.py
See above

2024-12-18 19:07 UTC, joglekara commented on tests/test_inverse/test_1d_random.py
I think there is some merit to having examples driven by tests and only maintaining one set of inputs. But I don't really care too much so we will leave it as is i.e. separate inputs for tests

2024-12-18 19:09 UTC, joglekara commented on tests/test_inverse/test_1d_random.py
fair. We should probably include `LossFunction` as part of these tests. We might want to split LossFunction into a scipy + optax wrapper (I think the LBFGS might really be worth it) + another class or set of methods that handle the rest of the stuff that isn't simply scipy + optax.

2024-12-18 19:10 UTC, joglekara commented on tsadar/core/physics/generate_spectra.py
Yeah I have no opinions about where but making the IRF functions into class methods is probably a good idea

2024-12-18 19:11 UTC, joglekara commented on tsadar/core/thomson_diagnostic.py
Sounds great

2024-12-24 16:35 UTC, joglekara commented on tsadar/inverse/fitter.py
Given the current refactoring, I think we should spend some time deciding on some sort of design spec for the inverse problem(s) now that we have some experience under our belt

2024-12-24 16:37 UTC, joglekara commented on tsadar/utils/data_handling/load_ts_data.py
pyhdf is not removed but moved to the conda requirements. I think we'll have to get rid of the requirements.txt altogether given this conflict and ambiguity

2024-12-24 16:37 UTC, joglekara commented on tsadar/utils/plotting/ele_fit_and_data (1).nc
done

2024-12-24 16:38 UTC, joglekara commented on tsadar/utils/plotting/plotters.py
yes. I think we should probably refactor the post processing flows and split them into separate functions for each of the 3 current operating modes

2024-12-24 16:38 UTC, joglekara commented on tsadar/utils/plotting/plotters.py
this was added because I wasn't able to get the 3d plot to work for whatever reason

2024-12-24 16:39 UTC, joglekara commented on tsadar/inverse/loss_function.py
100

2024-12-24 17:26 UTC, joglekara commented on tsadar/utils/plotting/plotters.py
yeah I was having some problems. this isn't necessarily the best solution. well want to think about this in the big post processing think

2024-12-24 17:28 UTC, joglekara commented on tsadar/utils/plotting/lineout_plot.py
I was having trouble with the plotting, I think because of some breaking changes to do with normalizing the output. We should probably just discuss this as part of the postprocessing design work

2024-12-24 17:29 UTC, joglekara commented on tsadar/utils/plotting/plotters.py
another thing that'll show up in the post processing design work

2024-12-24 17:31 UTC, joglekara commented on tsadar/inverse/fitter.py
yup, new distribution function implementation

2024-12-24 17:32 UTC, joglekara commented on tests/test_forward/test_1d.py
done

2024-12-24 17:32 UTC, joglekara commented on tests/test_forward/test_1d.py
fixed

2025-01-07 21:43 UTC, almilder commented on configs/1d/1d-new/defaults.yaml
Do we need the 1d and 1d-new input decks?

2025-01-07 21:46 UTC, almilder commented on test_arts1d_random.py
Should this be located within the tests folder?

2025-01-07 21:53 UTC, almilder commented on tests/test_inverse/test_1d_random.py
My concern is when a user goes to modify the input deck they would then break the test

2025-01-07 22:04 UTC, almilder reviewed
just a couple more minor note, primarily input deck stuff

2025-01-07 23:31 UTC, joglekara commented on configs/1d/1d-new/defaults.yaml
thought I got rid of these

2025-01-07 23:33 UTC, joglekara commented on test_arts1d_random.py
yes, removed from here now

2025-01-07 23:34 UTC, joglekara commented
> just a couple more minor note, primarily input deck stuff

good catches, done

2025-01-08 14:14 UTC, almilder approved these changes

2025-01-08 14:14 UTC, merged